---
abstract: 'Debug messages for smart logging to the file '
author: 'Kazuhiro Shibuya, C<< <k42uh1r0@gmail.com> >>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Debug-Smart
no_index:
  directory:
    - inc
    - t
requires:
  Path::Class: 0
  YAML: 0
  perl: 5.8.0
version: 0.002
